name: Golang Docker Build

on:
  release:
    types: [published]

env:
  CONTAINER_REPOSITORY: quay.io/vereeckenglenn # PUT YOUR OWN USERNAME HERE
  CONTAINER_IMAGE: alm-workshop
  GOLANG_VERSION: 1.23

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quay.io login
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: vereeckenglenn+testrobot
          password: ZINIRQKGK5NVC4AFUMB150076UA13V4KZSPLPRX5DTT7QTO24YUU9PEA66SPGGOU

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.CONTAINER_REPOSITORY }}/${{ env.CONTAINER_IMAGE }}:${{ github.event.release.tag_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
